//! macOS向けクリップボード監視実装（architecture.md 4.1章）。
//!
//! `NSPasteboard.general.changeCount`のポーリング方式（requirements.md 8章: macOSには
//! クリップボード変更のプッシュ通知APIが存在しないため）。既定400ms間隔、
//! メインウィンドウ（シェルフ/履歴パネル、Phase2ではタブ切り替えの単一ウィンドウ）が
//! 非表示中は800〜1000msへ緩和する（`set_panel_visible`で`window.rs`から通知される）。
//!
//! `#[cfg(target_os = "macos")]`配下のためこのLinux開発コンテナではコンパイル対象外であり、
//! 実機（macOS）での静的レビュー・実装意図の確認にとどまる（architecture.md 7章）。
//! `NSPasteboard.general`をメインスレッド以外から呼び出せるかはobjc2-app-kitのバージョンに
//! よってMainThreadMarker要求の有無が変わりうるため、実機ビルド時の確認が必要。

use std::sync::atomic::{AtomicBool, AtomicI64, Ordering};
use std::sync::Arc;
use std::time::Duration;

use objc2_app_kit::NSPasteboard;
use objc2_foundation::{NSArray, NSString};

use crate::error::ShelfError;

use super::{ClipboardSnapshot, ClipboardWatcher};

/// requirements.md 10.3章: NSPasteboardの除外UTI（Paste, Alfred等が準拠する事実上の標準）。
const EXCLUDE_TYPES: [&str; 3] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

/// メインウィンドウ表示中のポーリング間隔（既定400ms）。
const INTERVAL_VISIBLE_MS: u64 = 400;
/// メインウィンドウ非表示中の緩和後ポーリング間隔（800〜1000msの中間値を採用）。
const INTERVAL_HIDDEN_MS: u64 = 900;

/// メインウィンドウ（シェルフ/履歴パネル）の表示状態。`window.rs`のshow/hideから更新される。
static PANEL_VISIBLE: AtomicBool = AtomicBool::new(true);

/// `window.rs`から呼ばれる、パネルの表示状態変更通知。
pub fn set_panel_visible(visible: bool) {
    PANEL_VISIBLE.store(visible, Ordering::Relaxed);
}

pub struct MacClipboardWatcher {
    running: Arc<AtomicBool>,
    join_handle: Option<std::thread::JoinHandle<()>>,
}

impl MacClipboardWatcher {
    pub fn new() -> Self {
        Self {
            running: Arc::new(AtomicBool::new(false)),
            join_handle: None,
        }
    }
}

impl Default for MacClipboardWatcher {
    fn default() -> Self {
        Self::new()
    }
}

impl ClipboardWatcher for MacClipboardWatcher {
    fn start(
        &mut self,
        on_change: Box<dyn Fn(ClipboardSnapshot) + Send + Sync>,
    ) -> Result<(), ShelfError> {
        self.running.store(true, Ordering::SeqCst);
        let running = Arc::clone(&self.running);

        let join_handle = std::thread::Builder::new()
            .name("clipboard-watcher-mac".into())
            .spawn(move || poll_loop(running, on_change))
            .map_err(|e| ShelfError::Internal(format!("クリップボード監視スレッドの起動に失敗しました: {e}")))?;

        self.join_handle = Some(join_handle);
        Ok(())
    }

    fn stop(&mut self) {
        self.running.store(false, Ordering::SeqCst);
        if let Some(handle) = self.join_handle.take() {
            let _ = handle.join();
        }
    }
}

fn poll_loop(running: Arc<AtomicBool>, on_change: Box<dyn Fn(ClipboardSnapshot) + Send + Sync>) {
    let last_change_count = AtomicI64::new(-1);

    while running.load(Ordering::SeqCst) {
        unsafe {
            let pasteboard = NSPasteboard::generalPasteboard();
            let change_count = pasteboard.changeCount();

            if change_count as i64 != last_change_count.load(Ordering::SeqCst) {
                last_change_count.store(change_count as i64, Ordering::SeqCst);

                if !is_excluded_from_monitoring(&pasteboard) {
                    if let Some(snapshot) = read_snapshot(&pasteboard) {
                        on_change(snapshot);
                    }
                }
            }
        }

        let interval = if PANEL_VISIBLE.load(Ordering::Relaxed) {
            INTERVAL_VISIBLE_MS
        } else {
            INTERVAL_HIDDEN_MS
        };
        std::thread::sleep(Duration::from_millis(interval));
    }
}

/// requirements.md 10.3章の除外規約チェック。
unsafe fn is_excluded_from_monitoring(pasteboard: &NSPasteboard) -> bool {
    let Some(types) = pasteboard.types() else {
        return false;
    };
    EXCLUDE_TYPES.iter().any(|exclude| {
        let exclude_ns = NSString::from_str(exclude);
        types.containsObject(&exclude_ns)
    })
}

unsafe fn read_snapshot(pasteboard: &NSPasteboard) -> Option<ClipboardSnapshot> {
    // ファイルパス（Finderの「コピー」操作等）を最優先でチェックする
    if let Some(paths) = read_file_paths(pasteboard) {
        return Some(ClipboardSnapshot::FilePaths(paths));
    }
    if let Some(text) = read_text(pasteboard) {
        return Some(ClipboardSnapshot::Text(text));
    }
    if let Some(png) = read_image_as_png(pasteboard) {
        return Some(ClipboardSnapshot::Image(png));
    }
    None
}

unsafe fn read_text(pasteboard: &NSPasteboard) -> Option<String> {
    let ty = NSString::from_str("public.utf8-plain-text");
    let value = pasteboard.stringForType(&ty)?;
    Some(value.to_string())
}

unsafe fn read_file_paths(pasteboard: &NSPasteboard) -> Option<Vec<std::path::PathBuf>> {
    // レガシーだが単純な"NSFilenamesPboardType"（property list形式のファイルパス配列）を使う。
    // 近代的な`readObjectsForClasses:[NSURL class]`経由の実装は、Rust側でのNSURL⇄PathBufの
    // 変換コードが増えるため、Phase2の簡略化としてこちらを採用した（迷った設計判断）。
    let ty = NSString::from_str("NSFilenamesPboardType");
    let plist = pasteboard.propertyListForType(&ty)?;
    let array: objc2::rc::Retained<NSArray> = plist.downcast().ok()?;
    let paths = array
        .iter()
        .filter_map(|obj| obj.downcast::<NSString>().ok())
        .map(|ns_str| std::path::PathBuf::from(ns_str.to_string()))
        .collect::<Vec<_>>();
    if paths.is_empty() {
        None
    } else {
        Some(paths)
    }
}

unsafe fn read_image_as_png(pasteboard: &NSPasteboard) -> Option<Vec<u8>> {
    // "public.png"を優先し、無ければ"public.tiff"を`image`クレートでPNGへ再エンコードする
    let png_type = NSString::from_str("public.png");
    if let Some(data) = pasteboard.dataForType(&png_type) {
        return Some(data.to_vec());
    }

    let tiff_type = NSString::from_str("public.tiff");
    let data = pasteboard.dataForType(&tiff_type)?;
    let tiff_bytes = data.to_vec();
    let decoded = image::load_from_memory_with_format(&tiff_bytes, image::ImageFormat::Tiff).ok()?;
    let mut png_bytes = std::io::Cursor::new(Vec::new());
    decoded.write_to(&mut png_bytes, image::ImageFormat::Png).ok()?;
    Some(png_bytes.into_inner())
}
